### ISSUE TITLE
Cannot read anything :s

### ISSUE THREAD

**Issue by PJCzx** [eroak/rpi-433#6]
I'm currently testing on RPI2 B. Here is my `gpio readall` output

```
 +-----+-----+---------+------+---+-Model B2-+---+------+---------+-----+-----+
 | BCM | wPi |   Name  | Mode | V | Physical | V | Mode | Name    | wPi | BCM |
 +-----+-----+---------+------+---+----++----+---+------+---------+-----+-----+
 |     |     |    3.3v |      |   |  1 || 2  |   |      | 5v      |     |     |
 |   2 |   8 |   SDA.1 |   IN | 1 |  3 || 4  |   |      | 5V      |     |     |
 |   3 |   9 |   SCL.1 |   IN | 1 |  5 || 6  |   |      | 0v      |     |     |
 |   4 |   7 | GPIO. 7 |   IN | 1 |  7 || 8  | 1 | ALT0 | TxD     | 15  | 14  |
 |     |     |      0v |      |   |  9 || 10 | 1 | ALT0 | RxD     | 16  | 15  |
 |  17 |   0 | GPIO. 0 |   IN | 0 | 11 || 12 | 0 | IN   | GPIO. 1 | 1   | 18  |
 |  27 |   2 | GPIO. 2 |   IN | 0 | 13 || 14 |   |      | 0v      |     |     |
 |  22 |   3 | GPIO. 3 |  OUT | 0 | 15 || 16 | 1 | OUT  | GPIO. 4 | 4   | 23  |
 |     |     |    3.3v |      |   | 17 || 18 | 0 | IN   | GPIO. 5 | 5   | 24  |
 |  10 |  12 |    MOSI |   IN | 0 | 19 || 20 |   |      | 0v      |     |     |
 |   9 |  13 |    MISO |   IN | 0 | 21 || 22 | 0 | IN   | GPIO. 6 | 6   | 25  |
 |  11 |  14 |    SCLK |   IN | 0 | 23 || 24 | 1 | IN   | CE0     | 10  | 8   |
 |     |     |      0v |      |   | 25 || 26 | 0 | OUT  | CE1     | 11  | 7   |
 +-----+-----+---------+------+---+----++----+---+------+---------+-----+-----+
 |  28 |  17 | GPIO.17 |   IN | 0 | 51 || 52 | 0 | IN   | GPIO.18 | 18  | 29  |
 |  30 |  19 | GPIO.19 |   IN | 0 | 53 || 54 | 0 | OUT  | GPIO.20 | 20  | 31  |
 +-----+-----+---------+------+---+----++----+---+------+---------+-----+-----+
 | BCM | wPi |   Name  | Mode | V | Physical | V | Mode | Name    | wPi | BCM |
 +-----+-----+---------+------+---+-Model B2-+---+------+---------+-----+-----+
```

Because I use several other GPIO, I plugged two brand new Rx/Tx from the same bag like this:
Transmitter:
- VCC: Physical 2 (5V)
- GND: Physical 25 (0v)
- Txd: Physical 26 (wPi 11)

Receiver:
- VCC: Physical 4 (5V for 3,5V to 12V)
- GND: Physical 6 (0v)
- Rxd: Physical 11 (wPi 0)

![img_6726](https://cloud.githubusercontent.com/assets/2682199/15192797/104eb612-17bb-11e6-9b9b-aba76577a473.JPG)

I then execute this code as sudo user `sudo node exemple.js`

```
var rpi433    = require('rpi-433'),
    rfSniffer = rpi433.sniffer(0, 500), 
    rfSend    = rpi433.sendCode;

// Receive
rfSniffer.on('codes', function (code) {
  console.log('Code received: ', code);
});

// Send
rfSend(1234, 11, function(error, stdout) {   
  if(!error) console.log("Sending:", stdout);                       
});
```

And a get only this output:
`Sending: 1234`

I tried with and without antenna. Does any one of you have an idea if the RPI version can be the reason it's not working? I also tried by using GPIO 0 and 2 as in the exemple... nothing. I can't see what's wrong it my code.

Thx for your help

**Comment by FlorianWendelborn** [comment]
It's easily possible that your software is configured correctly, but that the signal just is too weak. I own similar RF transmitters and they are barely able to communicate over some centimeters. I'd suggest you to test this with a RF remote and hold the antenna right next to the RF receiver. Don't underestimate how weak the receiver is.

**Comment by PJCzx** [comment]
Thank you for your answer, I just retried with two different receivers (with antenna [17,3cm] & bran new). I pressed multiple buttons of multiples 433mHz remotes with feedback of the related devices. The remotes was touching the receivers. I read few articles on pulse delay [http://shop.ninjablocks.com/blogs/how-to/7506204-adding-433-to-your-raspberry-pi](url) (eg: `mySwitch.setPulseLength(207);`) into the `*.cpp` files. 

Is this related to the `debounce delay`? Should I try different values? What values? I'm a bit lost...
I bought these [https://www.amazon.fr/gp/product/B00V4ISS38/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1](url)
I'm considering buying other Rx/Tx to check if it can be somehow related. I prefer to triple check before "investing" money and time.

Thanks angain in advance

**Comment by eroak** [comment]
I'm sorry because i only tried rpi-433 on Raspberry 2. Maybe it's the reason of your issue. Is anyone has tested it on a Raspi 1 ? Wich Raspi is on your picture ? Raspi 1 ?

**Comment by FlorianWendelborn** [comment]
I'd suggest testing with a different library. That way we can exclude most hardware issues.

**Comment by eroak** [comment]
You should try to plug your Tx and Rx only on `GPIO[x]` pin

For your Tx, be carrefull and use a PIN which is in `OUT MODE` (GPIO3 or GPIO4) and update your code with the good pin number (GPIO3 => PIN 3 / GPIO4 => PIN 4).

For your Rx, could you test with the GPIO0 => PIN 0.

And another question : did you run your script with root privilege ? `sudo node myscript.js`

This is normal to only get `Sending: xxxx` and not have `Code received: xxxx` because there is a mecanism in `rpi-433` to avoid reading the code that we are sending. But maybe we should add an option for that.

I'm working on a new version that allows to set the pulseLength and get the pulseLength.

**Comment by PJCzx** [comment]
I also tried the GPIO X (0 OUT / 2 IN) without success. I always use `sudo` for `rpi-gpio` ;) still nothing. `rpi-gpio` is working on my install (tested with other projects). I didn't get your point on codes receiving. I'm at least expecting to trigger the event event if the code is not `1234`. But if I sent something, I expect to receive the same right? Thx

**Comment by eroak** [comment]
In fact, i think that your issue is not a bug but a mecanism inside `rpi-433` that avoid reading the code that we are sending.

I just published a new version `2.1.0` and i just remove this mecanism, could you try again please ?

**Comment by FlorianWendelborn** [comment]
@eroak That wouldn't explain this part though:

> I pressed multiple buttons of multiples 433mHz remotes with feedback of the related devices.

**Comment by PJCzx** [comment]
I splited my code into two separate scripts (rx.js and tx.js) and it finally works. It's maybe related to the speed access to the read/write actions. I now have to dig into the reason my remote controllers doesn't trigger any Rx event.

Thx everyone !

```
//rx.js

var rpi433    = require('rpi-433');

var rfSniffer = rpi433.sniffer({
      pin: 2,                     //Snif on GPIO 2 (or Physical PIN 13)
      debounceDelay: 500          //Wait 500ms before reading another code
    });

// Receive (data is like {code: xxx, pulseLength: xxx})
rfSniffer.on('data', function (data) {
  console.log('Code received: '+data.code+' pulse length : '+data.pulseLength);
});

console.log("Sniffing");
```

```
//tx.js

var rpi433    = require('rpi-433');

var rfEmitter = rpi433.emitter({
      pin: 0,                     //Send through GPIO 0 (or Physical PIN 11)
      pulseLength: 350            //Send the code with a 350 pulse length
    });

// Send
var f = function() {
        rfEmitter.sendCode(1234, function(error, stdout) {   //Send 1234
                if(!error) console.log(stdout); //Should display 1234
        });
};

setInterval(f, 5000);
```
